const express = require('express');
const os = require('os');

const app = express();
const PORT = 3000;

// Middleware to parse JSON
app.use(express.json());

app.use((req, res, next) => {
    const ts = new Date().toISOString();
    console.log(`[${ts}] ${req.method} ${req.url}  from=${req.ip || req.socket.remoteAddress}  ua=${(req.headers['user-agent'] || '-').slice(0, 50)}`);
    next();
});

// Store received SMS
let receivedSms = [];

// Middleware to validate API key from Bearer token
function validateApiKey(req, res, next) {
    const auth = req.headers['authorization'] || '';
    const token = auth.replace(/^Bearer\s+/i, '');
    if (!token) {
        return res.status(401).json({ success: false, error: 'Missing Authorization header' });
    }
    // Just log the API key in use; for testing, accept any non-empty token
    console.log(`🔑 API key used: ${token}`);
    next();
}

// POST endpoint that matches the Android app's expected path
app.post('/sms/forward', validateApiKey, (req, res) => {
    const sms = req.body;

    // Validate required fields
    if (!sms.message || !sms.sender) {
        return res.status(400).json({
            success: false,
            error: 'Missing required fields: message and sender'
        });
    }

    // Add timestamp if not provided
    if (!sms.timestamp) {
        sms.timestamp = new Date().toISOString();
    }

    // Store the SMS
    receivedSms.push(sms);

    // Log to console
    console.log('\n========================================');
    console.log('📱 SMS Received!');
    console.log('========================================');
    console.log(`From:        ${sms.sender}`);
    console.log(`Message:     ${sms.message}`);
    console.log(`Keyword:     ${sms.matchedKeyword || 'N/A'}`);
    console.log(`Device ID:   ${sms.deviceId || 'N/A'}`);
    console.log(`Device:      ${sms.deviceAlias || 'N/A'}`);
    console.log(`Time:        ${sms.timestamp}`);
    console.log('========================================\n');

    // Send success response
    res.json({
        success: true,
        message: 'SMS received successfully',
        id: receivedSms.length
    });
});

// Generic POST /api/sms alias (also works)
app.post('/api/sms', validateApiKey, (req, res) => {
    const sms = req.body;
    if (!sms.message || !sms.sender) {
        return res.status(400).json({ success: false, error: 'Missing required fields' });
    }
    if (!sms.timestamp) sms.timestamp = new Date().toISOString();
    receivedSms.push(sms);
    console.log(`\n📱 SMS (api/sms) from ${sms.sender}: ${sms.message}\n`);
    res.json({ success: true, id: receivedSms.length });
});

// GET endpoint to view all received SMS
app.get('/api/sms', (req, res) => {
    res.json({
        count: receivedSms.length,
        messages: receivedSms
    });
});

app.delete('/api/sms', (req, res) => {
    const count = receivedSms.length;
    receivedSms = [];
    console.log(`\n🗑️  Cleared ${count} stored message(s)\n`);
    res.json({
        success: true,
        cleared: count
    });
});

// GET endpoint to check server status
app.get('/api/status', (req, res) => {
    res.json({
        status: 'ok',
        uptime: process.uptime(),
        receivedCount: receivedSms.length
    });
});

// Get local IP address
function getLocalIp() {
    const interfaces = os.networkInterfaces();
    for (const name of Object.keys(interfaces)) {
        for (const iface of interfaces[name]) {
            if (iface.family === 'IPv4' && !iface.internal) {
                return iface.address;
            }
        }
    }
    return '127.0.0.1';
}

// Start server
app.listen(PORT, () => {
    const localIp = getLocalIp();
    console.log('🚀 SMS Monitor Test Backend');
    console.log('============================');
    console.log(`Server running at:`);
    console.log(`  - Local:   http://localhost:${PORT}`);
    console.log(`  - Network: http://${localIp}:${PORT}`);
    console.log('');
    console.log('Endpoints:');
    console.log(`  POST /sms/forward - Receive SMS (Android app endpoint)`);
    console.log(`  POST /api/sms     - Receive SMS (generic alias)`);
    console.log(`  GET  /api/sms     - View all received SMS`);
    console.log(`  GET  /api/status  - Server status`);
    console.log('');
    console.log('Configure your Android app with:');
    console.log(`  Backend URL: http://${localIp}:${PORT}`);
    console.log('  (API key is auto-generated by the app)');
    console.log('============================');
});